### ISSUE TITLE
Installing Swagger

### ISSUE THREAD

**Issue by hajsf** [bervProject/ODataTutorial#27]
Thanks for the great tutorial, but looks you missed mentioning the installtion required for:
```c#
Swashbuckle.AspNetCore.Swagger
Swashbuckle.AspNetCore.SwaggerGen
Swashbuckle.AspNetCore.SwaggerUI
```

**Comment by berviantoleo** [comment]
Thanks for the feedback. I'm using `Swashbuckle.AspNetCore.Swagger` that's come from the template, but I'm not sure how the current behavior of the existing template.

I will add it if you find it will be helpful.

Thank you.

**Comment by hajsf** [comment]
> I will add it if you find it will be helpful.

Actually it is, today I stuck with 2 things, as I've fresh installation, 
1. Could not find the nuget, so I found a solution here: https://stackoverflow.com/a/62989469/2441637
2. Could not find the swagger, so I found a solution here: https://stackoverflow.com/a/64516385

**Comment by berviantoleo** [comment]
I've added your suggestion. If you think that's ok, I will close this issue.

**Comment by hajsf** [comment]
Thanks a lot, hope other will get benefit from it as well.
